CMEMS_datasets_options = {'cmems_SST_MED_SST_L4_REP_OBSERVATIONS_010_021':{'varname':  "analysed_sst", "prod_type": 'REP',
                                                                        #  'grid_file':"prev/cell_areas_CMS.nc",
                                                                         'grid_file':"cell_areas_CMS.nc",
                                                                         'grid_url': 'https://data.d4science.net/RNaQ', 
                                                                         'clim_file':"CMS_SST_Climatology_19872021.nc",
                                                                         'clim_url': 'https://data.d4science.net/YB7c'},
                        'SST_MED_SST_L4_NRT_OBSERVATIONS_010_004_a_V2': {'varname':  "analysed_sst", "prod_type": 'NRT',
                                                                        #  'grid_file':"2024/cell_areas_CMS_NRT.nc",
                                                                         'grid_file':"cell_areas_CMS_NRT.nc",
                                                                         'grid_url': 'https://data.d4science.net/kyvw',
                                                                         'clim_file':"CMS_SST_Climatology_19872021_rect00625.nc",
                                                                         'clim_url': 'https://data.d4science.net/Sx86'},
}