# docker build --platform linux/amd64 -t fpalermo/bc2026-mhw-pip:v0.1.0 .
FROM python:3.11-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gfortran git ca-certificates wget curl pkg-config \
    libproj-dev proj-data proj-bin libgeos-dev libgdal-dev libnetcdf-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./

RUN python -m pip install --upgrade pip setuptools wheel \
    && pip install --no-cache-dir -r ./requirements.txt
